### ISSUE TITLE
Could not find uniform_notifier-1.13.0 in any of the sources

### ISSUE THREAD

**Issue by aniketstiwari** [flyerhzm/uniform_notifier#59]
When running CI I am getting this issue. I tried to downgrade the uniform_notifier version but still it didn't work for me

Bundler::GemNotFound: Could not find uniform_notifier-1.13.0 in any of the sources
/var/lib/jenkins/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/bundler/spec_set.rb:91:in `block in materialize'
/var/lib/jenkins/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/bundler/spec_set.rb:85:in `map!'
/var/lib/jenkins/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/bundler/spec_set.rb:85:in `materialize'
/var/lib/jenkins/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/bundler/definition.rb:170:in `specs'
/var/lib/jenkins/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/bundler/definition.rb:237:in `specs_for'
/var/lib/jenkins/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/bundler/definition.rb:226:in `requested_specs'
/var/lib/jenkins/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:108:in `block in definition_method'
/var/lib/jenkins/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:20:in `setup'
/var/lib/jenkins/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/bundler.rb:107:in `setup'
/var/lib/jenkins/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/bundler/setup.rb:20:in `<top (required)>'
/var/lib/jenkins/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/var/lib/jenkins/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/var/lib/jenkins/workspace/Reskinning_test/config/boot.rb:4:in `<top (required)>'
/var/lib/jenkins/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/var/lib/jenkins/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/var/lib/jenkins/workspace/Reskinning_test/config/application.rb:1:in `<top (required)>'
/var/lib/jenkins/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/var/lib/jenkins/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/var/lib/jenkins/workspace/Reskinning_test/Rakefile:5:in `<top (required)>'
/var/lib/jenkins/.rvm/gems/ruby-2.4.2/gems/rake-13.0.1/lib/rake/rake_module.rb:29:in `load'
/var/lib/jenkins/.rvm/gems/ruby-2.4.2/gems/rake-13.0.1/lib/rake/rake_module.rb:29:in `load_rakefile'
/var/lib/jenkins/.rvm/gems/ruby-2.4.2/gems/rake-13.0.1/lib/rake/application.rb:703:in `raw_load_rakefile'
/var/lib/jenkins/.rvm/gems/ruby-2.4.2/gems/rake-13.0.1/lib/rake/application.rb:104:in `block in load_rakefile'
/var/lib/jenkins/.rvm/gems/ruby-2.4.2/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/var/lib/jenkins/.rvm/gems/ruby-2.4.2/gems/rake-13.0.1/lib/rake/application.rb:103:in `load_rakefile'
/var/lib/jenkins/.rvm/gems/ruby-2.4.2/gems/rake-13.0.1/lib/rake/application.rb:82:in `block in run'
/var/lib/jenkins/.rvm/gems/ruby-2.4.2/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/var/lib/jenkins/.rvm/gems/ruby-2.4.2/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'
/var/lib/jenkins/.rvm/gems/ruby-2.4.2/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/var/lib/jenkins/.rvm/gems/ruby-2.4.2/bin/rake:23:in `load'
/var/lib/jenkins/.rvm/gems/ruby-2.4.2/bin/rake:23:in `<main>'

In my GemFile.lock it is a dependency of Bullet Gem

bullet (6.1.0)
      activesupport (>= 3.0.0)
      uniform_notifier (~> 1.11)

**Comment by aniketstiwari** [comment]
I resolved it by upgrading the ruby version in the CI from 2.4.2 to 2.5.3. Hence closing the issue
